#!/usr/bin/env python3

import sys
from pathlib import Path

import npimage

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: dmo_transfer_metadata <input_image> <output_image>")
        sys.exit(1)

    metadata_path = sys.argv[1]
    image_path = sys.argv[2]

    metadata = npimage.load(metadata_path, return_metadata=True)[1]
    im = npimage.load(image_path)

    if image_path.endswith('nrrd'):
        # Stick _newmetadata into the filename
        output_path = image_path.rsplit('.', 1)[0] + '_newmetadata.nrrd'
    else:
        output_path = Path(image_path).with_suffix('.nrrd')

    # Transfer metadata to the output image
    npimage.save(im, output_path, metadata=metadata)
